Suggestions on the initial toolbox PR
broadinstitute/gnomad-toolbox pull request #5
Opened 2024-12-11 05:49 UTC by jkgoodrich

2024-12-13 18:07 UTC, KoalaQin requested changes
I'm sending these over for now because I need 1 of them for testing.

2024-12-18 15:07 UTC, KoalaQin requested changes
Thank you for making this PR, your new structure of code makes more sense! 
I think we can merge yours after some changes and I could work on the to-dos.

2024-12-18 15:54 UTC, jkgoodrich commented on gnomad_toolbox/filtering/variant.py
> +        )
really? I got the warning

2024-12-18 16:01 UTC, jkgoodrich commented on README.md
> +# TODO: Add fully detailed info about how to install and open the notebooks.
Sounds good, but don't add anything yet. First step is to get a bunch of tickets in for todo's and we can decide who will tackle what

2024-12-18 16:03 UTC, jkgoodrich commented on gnomad_toolbox/filtering/variant.py
> +    # TODO: Consider this alternative approach to get the intervals from gencode. That
OK, lets go with the faster way and a filter so we get the same numbers as the browser would get. For now lets just add a TODO and a ticket to do it

2024-12-18 18:18 UTC, KoalaQin commented on gnomad_toolbox/filtering/variant.py
> +        )
Yeah, it's working, but it was printed after the init cell. ![Screenshot 2024-12-18 at 1 17 25 PM](https://github.com/user-attachments/assets/37d20a98-7a40-47bb-9dc8-207b801da566)

2024-12-18 18:20 UTC, KoalaQin commented on gnomad_toolbox/filtering/variant.py
> +        )
it's just a hail/notebook thing.

2024-12-18 18:20 UTC, KoalaQin approved these changes
LGTM!

2024-12-18 18:38 UTC, merged